services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~P9kP1bWf"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_y2prWleKSN8T@ep-old-haze-a41x4qie-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
